### ISSUE TITLE
Compile a smart set of rules from all the AddonGroups

### ISSUE THREAD

**Issue by rehandalal** [mozilla/morgoth#41]
We need to take the entire set of `AddonGroup` objects and create an appropriate set of Balrog release and rule data from them. This issue does not cover actually syncing that data to Balrog, just creating the actual JSON blobs for the rule/release set.

**Comment by rhelmer** [comment]
> This issue does not cover actually syncing that data to Balrog, just creating the actual JSON blobs for the rule/release set.

@rehandalal - do we have an example of these JSON blobs that I can develop against?

**Comment by rhelmer** [comment]
> do we have an example of these JSON blobs that I can develop against?

https://gist.github.com/rehandalal/7b1fe140c08e81ed18ec6e8c67fbe375

**Comment by rhelmer** [comment]
From meetings with @mozbhearsum and other interested partied we concluded that this isn't something we want to do; Morgoth AddonGroups should instead target very specific releases of Firefox.
